extension_dir="C:\Users\hamak\OneDrive\Desktop\koga.orginal\ext"
extension=curl
extension=fileinfo
extension=gd
extension=mbstring
extension=openssl
extension=pdo_mysql
extension=mysqli
extension=zip
date.timezone=UTC
